language: julia
os:
  - osx
  - linux
julia:
  - nightly
  - 0.4
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("CSV"); Pkg.test("CSV"; coverage=true)';
after_success:
  - julia -e 'cd(Pkg.dir("CSV")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("CSV")); include(joinpath("docs", "make.jl"))'
#  - julia -e 'cd(Pkg.dir("CSV")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';
