language: julia

os:
  - linux
  - osx

julia:
  - 0.5
  - nightly

notifications:
  email: false

after_success:
  - julia -e 'cd(Pkg.dir("CSV")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("CSV")); include(joinpath("docs", "make.jl"))'
  - julia -e 'Pkg.add("PkgBenchmark")'
  - julia -e 'using PkgBenchmark; benchmarkpkg("CSV"; promptsave=false, promptoverwrite=false)'
