site_name:        CSV.jl
repo_url:         https://github.com/JuliaData/CSV.jl
site_description: Utility library for working with CSV and other delimited files in the Julia programming language
site_author:      Jacob Quinn

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
